site_name: detection-datasets
site_description: Easily load and transform datasets for object detection
site_url: https://blinjrm.github.io/detection-datasets/

theme:
  name: material
  logo: assets/logo.png

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  features:
    - navigation.tabs

plugins:
  - mkdocstrings
  - section-index
  - search

nav:
  - Quick-start: index.md
  - Tutorial: tutorials.md
  - How-to guides: how-to-guides.md
  - Reference:
      - reference/index.md
      - DetectionDataset: reference/detection_dataset.md
      - Bbox: reference/bbox.md
      - Readers: reference/readers.md
      - Writers: reference/writers.md
  - Explanation: explanation.md

markdown_extensions:
  - toc:
      permalink: "#"

repo_url: https://github.com/blinjrm/detection-datasets
edit_uri: ""
